### ISSUE TITLE
Check on شوارع أميركا 

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad-Product-Marketing#23]
(Details in the email sent by Farah)

**Comment by Nur-alfayez** [comment]
I think we have 2 options: 

- Talk to Lightpenco to see how much it would cost to make a 1 min promo with human element. A very simple one at ZINC or something. 
- Talk to Lightpenco to see how much add voiceover to the video.

**Comment by Nur-alfayez** [comment]
Talked to Alaa, he will send us a couple of options/ideas soon. @EmanHylooz

**Comment by EmanHylooz** [comment]
Perfect (y)

Best,

Eman Hylooz

Founder & CEO | Abjjad

Jordan: +962.79.5402965 | Lebanon: +961.81.667918 | *www.abjjad.com*
<http://www.abjjad.com/>
