### ISSUE TITLE
Check on the dude who did a video about Abjjad

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad-Product-Marketing#24]
-Check on ways of how to use this video and make sure he knows we did by tagging him. 
(Details about him and his accounts in the email thread from Farah)

**Comment by Nur-alfayez** [comment]
Do you remember the name of the guy? can't find him. @EmanHylooz

**Comment by EmanHylooz** [comment]
Check our twitter account. I retweeted and stuff. He is Saudi.
