### ISSUE TITLE
Some Onboarding ideas for the App

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad-Product-Marketing#39]
- Try the onboarding for Blinkist 
https://itunes.apple.com/app/id568839295?mt=8&pt=com.blinkslabs.Blinkist&ct=WebLeads
- Try the onboarding for fortunica 
https://itunes.apple.com/us/app/fortunica-psychic-reading-tarot-advice/id602283488?mt=8

**Comment by Nur-alfayez** [comment]
Onboarding before signup
Email from itunes  not from signup
