### ISSUE TITLE
Keep an eye on when we reach 400K users so we celebrate them. 

### ISSUE THREAD

**Issue by Nur-alfayez** [EmanHylooz/Abjjad-Product-Marketing#42]

**Comment by EmanHylooz** [comment]
we did :)  We have now 400,597  users.
Lets celebrate :)

Best,

Eman Hylooz

Founder & CEO | Abjjad

Jordan: +962.79.5402965 | Lebanon: +961.81.667918 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by Nur-alfayez** [comment]
شو نحكي؟ 

شكراً للأبجديين
٤٠٠ قارئ على أبجد

قارئ ولا مستخدم؟

**Comment by EmanHylooz** [comment]
I guess عضو
we used to say من أعضاء أبجد.. عضو في أبجد .. عضو مسجّل في أبجد

Best,

Eman Hylooz

Founder & CEO | Abjjad

Jordan: +962.79.5402965 | Lebanon: +961.81.667918 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by Nur-alfayez** [comment]
![celebrating 400 user](https://user-images.githubusercontent.com/29916678/29319094-67d1853c-81db-11e7-974e-4ffeafad16d7.jpg)

**Comment by EmanHylooz** [comment]
(y)

Best,

Eman Hylooz

Founder & CEO | Abjjad

Jordan: +962.79.5402965 | Lebanon: +961.81.667918 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by Nur-alfayez** [comment]
وصلنا ل ٤٠٠ ألف عضو في أبجد! 
شكراً للأبجدين الذين يثرون أبجد بتقييماتهم ومراجعاتهم لآلاف الكتب والذين لولاهم يصعب علينا الإجابة على "ماذا أقرأ الآن؟" :-) 
 

شو رأيك؟

**Comment by Nur-alfayez** [comment]
للأبجديين
