### ISSUE TITLE
Look for tools for push 

### ISSUE THREAD

**Issue by Nur-alfayez** [EmanHylooz/Abjjad-Product-Marketing#55]
And then have a call with Shimaa.

**Comment by Nur-alfayez** [comment]
@EmanHylooz what was the recent thing you agreed on with shimaa? am I still needed to look for tools?

**Comment by EmanHylooz** [comment]
No no need. We will go for a vombination of onsigal( or pushbots) with
server side

**Comment by Nur-alfayez** [comment]
(y)
