### ISSUE TITLE
Social media 

### ISSUE THREAD

**Issue by Nur-alfayez** [EmanHylooz/Abjjad-Product-Marketing#9]
- Decide on goals (whats our main 3 goals from social media? ex: increase engagement, installs, insights on users and their problem (surveys), instilling core value in users..). 
- Decide on metrics to measure the goals (CTR, reach, engagement on posts, ...) 
- Decide on direction to achieve goals (including style, content, and voice)
- Decide on specific tactics to reach goals (post vague branding to see if they get it - like the jeans and phone, likes and interactions on instagram, tagging publishers, looking for partners /influencers..)
- Structure previous points inside content calendar and communicate with Nancy.

**Comment by Nur-alfayez** [comment]
@EmanHylooz how about we meet tomorrow at 10:30 am to discuss this?

**Comment by EmanHylooz** [comment]
Sure. Can we make it 11:30?

**Comment by Nur-alfayez** [comment]
Yeah sure

**Comment by Nur-alfayez** [comment]
**Keep in mind creating a stock of quotes / book titles to feature for Nancy.**

**Comment by Nur-alfayez** [comment]
- Goals: 
1. Core value mostly through: content discovery (e-books, reviews, quotes, readers - discover content through users) it could be the core value: access to e-books and opinions not available else where). Abjadeyyoon. * Did you know what Abjadeyyat mean? with the GIF thing. 
2. Engagement: through highlighting features and others. 
3. Community building: increasing relevant stakeholders (readers, publishers, authors).

**Comment by Nur-alfayez** [comment]
Post about books we don't have to highlight notify me once available.

**Comment by Nur-alfayez** [comment]
PDF VS e-books (funny post find the differences)

**Comment by Nur-alfayez** [comment]
Metrics: 

1. Core value: quality insights through comments (look into other ways of measuring...)
2. Engagement: per post, more about the content
3. Community building: followers, shares, mentions, and tags. 

When publishers share our posts, we reached a goal. 
Make tags more personal with authors and publishers, about their journey. Even for the publishers posts.

**Comment by Nur-alfayez** [comment]
Direction: 

- Making reading cool
- Personal, revolves around users 
- Insightful, in-depth info, rich content about books (from Press ...) 
- Away from religious content, ... when controversial, ask for what they think and state that its controversial
- Moderating comments (calm down if someone mad, ask for more, just like a panel). 

Tactics: 
- read my books on abjjad (videos with authors) 
- Sharing a good book review about the book by author, makes it worth sharing by author. 
- Short movies for FAQ, or for core value element. Highlight users, making reading cool: series of facts about reading/libraries/.. highlight authors and their stories. 

- FB live with Ahmad (and Eman to introduce him in a short video).

**Comment by Nur-alfayez** [comment]
Include Twitter.

**Comment by EmanHylooz** [comment]
@Nur-alfayez while posting on abjjad today, I found that they have new features. Try to post, you will find that there is a way to add a product, or a button to the post (like a button that says send message). Worth exploring. 

![image](https://user-images.githubusercontent.com/6830380/29509110-c54a3c30-865f-11e7-8d48-71c58e9224e2.png)

**Comment by Nur-alfayez** [comment]
Sure will check it out.

**Comment by EmanHylooz** [comment]
An ides: 
To post from eBooks من القائل?

**Comment by Nur-alfayez** [comment]
Nice, yeah we can do same orange style
